// <auto-generated />
namespace Attest.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterTable_Application_ModifiedDatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterTable_Application_ModifiedDatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201608230257596_AlterTable_Application_ModifiedDatetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
